import { Group, Home, Restroom, Briefcase, Calendar, Baby } from "grommet-icons";

export const polishEnglishConfig = {
  family: {
    value: [
      { polish: "adopcja", english: "adoption" },
      { polish: "przodek", english: "ancestor" },
      { polish: "ciotka", english: "aunt" },
      { polish: "brat", english: "brother" },
      { polish: "szwagier", english: "brother-in-law" },
      { polish: "dziecko", english: "child" },
      { polish: "kuzyn / kuzynka", english: "cousin" },
      { polish: "córka", english: "daughter" },
      { polish: "synowa", english: "daughter-in-law" },
      { polish: "potomek", english: "descendant" },
      { polish: "rozwód", english: "divorce" },
      { polish: "starsza siostra", english: "elder sister" },
      { polish: "dalsza rodzina", english: "extended family" },
      { polish: "życie rodzinne", english: "family life" },
      { polish: "spotkanie rodzinne", english: "family reunion" },
      { polish: "rodzina", english: "family" },
      { polish: "teść", english: "father-in-law" },
      { polish: "rodzina zastępcza", english: "foster family" },
      { polish: "przybrane dziecko", english: "foster-child" },
      { polish: "pokolenie", english: "generation" },
      { polish: "wnuki", english: "grandchildren" },
      { polish: "dziadek", english: "grandfather" },
      { polish: "babcia", english: "grandmother" },
      { polish: "wnuk", english: "grandson" },
      { polish: "brat przyrodni", english: "half-brother" },
      { polish: "siostra przyrodnia", english: "half-sister" },
      { polish: "mąż", english: "husband" },
      { polish: "żyć w separacji", english: "to live in separation" },
      { polish: "małżeństwo", english: "marriage" },
      { polish: "zamężna", english: "married" },
      { polish: "poślubić kogoś", english: "to marry someone" },
      { polish: "mama", english: "mother" },
      { polish: "teściowa", english: "mother-in-law" },
      {
        polish: "rodzina wielopokoleniowa",
        english: "multi-generation family",
      },
      { polish: "siostrzeniec", english: "nephew" },
      { polish: "najbliższy krewny", english: "next of kin" },
      { polish: "siostrzenica", english: "niece" },
      { polish: "rodzina wielodzietna", english: "numerous family" },
      { polish: "jedynak", english: "only child" },
      { polish: "sierota", english: "orphan" },
      { polish: "rodzice", english: "parents" },
      { polish: "założyć rodzinę", english: "to raise a family" },
      { polish: "krewni", english: "relatives" },
      { polish: "siostra", english: "sister" },
      { polish: "bratowa", english: "sister-in-law" },
      { polish: "syn", english: "son" },
      { polish: "zięć", english: "son-in-law" },
      { polish: "ojczym", english: "step-father" },
      { polish: "macocha", english: "step-mother" },
      { polish: "bliźniak", english: "twin" },
      { polish: "wujek", english: "uncle" },
      { polish: "wychowanie", english: "upbringing" },
      { polish: "wdowa", english: "widow" },
      { polish: "wdowiec", english: "widower" },
      { polish: "żona", english: "wife" },
    ],
    name: {
      polish: "Rodzina",
      english: "Family",
    },
    Icon: Group,
  },
  houseAndAccommodation: {
    name: {
      english: "House and accommodation",
      polish: "Dom i zakwaterowanie",
    },
    value: [
      { polish: "budzik", english: "alarm clock" },
      { polish: "fotel", english: "armchair" },
      { polish: "łóżko", english: "bed" },
      { polish: "łóżko piętrowe", english: "bunk beds" },
      { polish: "dywan", english: "carpet" },
      { polish: "krzesło", english: "chair" },
      { polish: "pojemnik", english: "container" },
      { polish: "filiżanka", english: "cup" },
      { polish: "zasłona", english: "curtain" },
      { polish: "sztućce", english: "cutlery" },
      { polish: "zmywarka", english: "dishwasher" },
      { polish: "szuflada", english: "drawer" },
      { polish: "podłoga", english: "floor" },
      { polish: "widelec", english: "fork" },
      { polish: "zamrażarka", english: "freezer" },
      { polish: "lodówka", english: "fridge" },
      { polish: "meble", english: "furniture" },
      { polish: "szklanka", english: "glass" },
      { polish: "grzejnik", english: "heater" },
      { polish: "nóż", english: "knife" },
      { polish: "lampa", english: "lamp" },
      { polish: "zamek", english: "lock" },
      { polish: "lustro", english: "mirror" },
      { polish: "kubek", english: "mug" },
      { polish: "piekarnik", english: "oven" },
      { polish: "patelnia", english: "pan" },
      { polish: "mebel", english: "piece of furniture" },
      { polish: "kaloryfer", english: "radiator" },
      { polish: "prześcieradło", english: "sheet" },
      { polish: "zlewozmywak", english: "sink" },
      { polish: "mydło", english: "soap" },
      { polish: "sofa / kanapa", english: "sofa" },
      { polish: "łyżka", english: "spoon" },
      { polish: "stół", english: "table" },
      { polish: "obrus", english: "tablecloth" },
      { polish: "zastawa stołowa", english: "tableware" },
      { polish: "latarka", english: "torch" },
      { polish: "szafa", english: "wardrobe" },
      { polish: "umywalka", english: "washbasin" },
      { polish: "pralka", english: "washing machine" },
      { polish: "zakwaterowanie", english: "accommodation" },
      { polish: "strych", english: "attic" },
      { polish: "balkon", english: "balcony" },
      { polish: "łazienka", english: "bathroom" },
      { polish: "sypialnia", english: "bedroom" },
      { polish: "sufit", english: "ceiling" },
      { polish: "piwnica", english: "cellar" },
      { polish: "centralne ogrzewanie", english: "central heating" },
      { polish: "komin", english: "chimney" },
      { polish: "korytarz", english: "corridor" },
      { polish: "jadalnia", english: "dining room" },
      { polish: "drzwi", english: "door" },
      { polish: "wycieraczka do butów", english: "door mat" },
      { polish: "dzwonek do drzwi", english: "doorbell" },
      { polish: "dom jednorodzinny", english: "family house" },
      { polish: "kominek", english: "fireplace" },
      { polish: "mieszkanie", english: "flat / apartment" },
      { polish: "poddasze", english: "garret" },
      { polish: "furtka", english: "gate" },
      { polish: "przedpokój", english: "hall" },
      { polish: "żywopłot", english: "hedge" },
      { polish: "dom", english: "house" },
      { polish: "właściciel domu", english: "house owner" },
      { polish: "domofon", english: "house telephone" },
      { polish: "kuchnia", english: "kitchen" },
      { polish: "skrzynka na listy", english: "letterbox" },
      { polish: "oświetlenie", english: "lighting" },
      { polish: "piorunochron", english: "lightning rod" },
      { polish: "pokój dzienny", english: "living room" },
      { polish: "hipoteka", english: "mortgage" },
      { polish: "wprowadzić się", english: "to move in" },
      { polish: "wyprowadzić się", english: "to move out" },
      { polish: "nieruchomość", english: "real estate" },
      { polish: "czynsz", english: "rent" },
      { polish: "dach", english: "roof" },
      { polish: "pokój", english: "room" },
      { polish: "bieżąca woda", english: "running water" },
      { polish: "bliźniak", english: "semi-detached house" },
      { polish: "kanalizacja", english: "sewage system" },
      { polish: "apartament", english: "suite" },
      { polish: "czynszowy", english: "tenement" },
      { polish: "próg", english: "threshold" },
      { polish: "toaleta", english: "toilet" },
      { polish: "judasz / wizjer", english: "view finder" },
      { polish: "boazeria", english: "wainscot" },
      { polish: "ściana", english: "wall" },
      { polish: "okno", english: "window" },
      { polish: "parapet", english: "window sill" },
    ],
    Icon: Home,
  },
  hygiene: {
    value: [
      { polish: "bidet", english: "bidet" },
      { polish: "wągier", english: "black-head" },
      { polish: "myć zęby", english: "to brush teeth" },
      { polish: "czyścić", english: "clean" },
      { polish: "czesać włosy", english: "to comb hair" },
      { polish: "brud", english: "dirt" },
      { polish: "brudny", english: "dirty" },
      { polish: "piłować paznokcie", english: "to file nails" },
      { polish: "spłukać toaletę", english: "to flush the toilet" },
      { polish: "brać prysznic", english: "to have a shower" },
      { polish: "higiena", english: "hygiene" },
      { polish: "higieniczny", english: "hygienic" },
      { polish: "sedes", english: "lavatory seat" },
      { polish: "płukać włosy", english: "to rinse hair" },
      { polish: "płukać usta / wypłukać usta", english: "to rinse mouth" },
      { polish: "golenie", english: "shaving" },
      { polish: "mydelniczka", english: "soap dish" },
      { polish: "mydło", english: "soap" },
      { polish: "gąbka", english: "sponge" },
      { polish: "toaleta", english: "toilet" },
      { polish: "szczoteczka do zębów", english: "toothbrush" },
      { polish: "pasta do zębów", english: "toothpaste" },
      { polish: "ręcznik", english: "towel" },
      { polish: "pisuar", english: "urinal" },
      { polish: "myć włosy", english: "to wash hair" },
      { polish: "myć się", english: "to wash" },
      { polish: "umywalka", english: "washbasin" },
    ],
    name: {
      english: 'Hygiene',
      polish: 'Higiena',
    },
    Icon: Restroom,
  },
  personalBelongings: {
    value: [
      { polish: 'saszetka', english: 'bag' },
      { polish: 'pudełko zapałek', english: 'box of matches' },
      { polish: 'bransoleta', english: 'bracelet' },
      { polish: 'aktówka', english: 'briefcase' },
      { polish: 'kalendarz', english: 'calendar' },
      { polish: 'czapka', english: 'cap' },
      { polish: 'kluczyki do samochodu', english: 'car keys' },
      { polish: 'łańcuszek', english: 'chain' },
      { polish: 'guma do żucia', english: 'chewing gum' },
      { polish: 'moneta', english: 'coin' },
      { polish: 'grzebień', english: 'comb' },
      { polish: 'szkła kontaktowe', english: 'contact lens' },
      { polish: 'karta kredytowa', english: 'credit card' },
      { polish: 'nić dentystyczna', english: 'dental thread' },
      { polish: 'dezodorant', english: 'deodorant' },
      { polish: 'terminarz', english: 'diary' },
      { polish: 'kolczyk', english: 'earring' },
      { polish: 'pióro wieczne', english: 'fountain pen' },
      { polish: 'okulary', english: 'glasses' },
      { polish: 'chusteczka do nosa', english: 'handkerchief' },
      { polish: 'kapelusz', english: 'hat' },
      { polish: 'klejnot', english: 'jewel' },
      { polish: 'biżuteria', english: 'jewellery' },
      { polish: 'klucz', english: 'key' },
      { polish: 'laptop', english: 'laptop' },
      { polish: 'zapalniczka', english: 'lighter' },
      { polish: 'szminka', english: 'lipstick' },
      { polish: 'medalionik', english: 'locket' },
      { polish: 'telefon komórkowy', english: 'mobile phone' },
      { polish: 'pieniądze', english: 'money' },
      { polish: 'pilniczek do paznokci', english: 'nail file' },
      { polish: 'nożyczki do paznokci', english: 'nail scissors' },
      { polish: 'naszyjnik', english: 'necklace' },
      { polish: 'paszport', english: 'passport' },
      { polish: 'pióro', english: 'pen' },
      { polish: 'ołówek', english: 'pencil' },
      { polish: 'wisiorek', english: 'pendant' },
      { polish: 'karta telefoniczna', english: 'phone card' },
      { polish: 'puderniczka', english: 'powder puff' },
      { polish: 'portmonetka', english: 'purse' },
      { polish: 'golarka', english: 'razor' },
      { polish: 'pierścionek', english: 'ring' },
      { polish: 'szalik', english: 'scarf' },
      { polish: 'nożyczki', english: 'scissors' },
      { polish: 'szampon', english: 'shampoo' },
      { polish: 'mydło', english: 'soap' },
      { polish: 'okulary przeciwsłoneczne', english: 'sunglasses' },
      { polish: 'papier toaletowy', english: 'toilet paper' },
      { polish: 'pasta do zębów', english: 'toothpaste' },
      { polish: 'wykałaczka', english: 'toothpick' },
      { polish: 'ręcznik', english: 'towel' },
      { polish: 'bielizna', english: 'underwear' },
      { polish: 'kosmetyczka', english: 'vanity case' },
      { polish: 'portfel', english: 'wallet' },
      { polish: 'zegarek', english: 'watch' },
      { polish: 'obrączka', english: 'wedding ring' },
    ],
    name: {
      english: 'Personal belongings',
      polish: 'Przedmioty osobiste',
    },
    Icon: Briefcase,
  },
  dailyActivites: {
    value: [
      { polish: 'spieszyć się', english: 'to be in a hurry' },
      { polish: 'czyścić', english: 'to clean' },
      { polish: 'czesać', english: 'to comb' },
      { polish: 'gotować obiad', english: 'to cook dinner' },
      { polish: 'gotować', english: 'to cook' },
      { polish: 'gimnastykować się', english: 'to do exercises' },
      { polish: 'pić', english: 'to drink' },
      { polish: 'suszyć', english: 'to dry' },
      { polish: 'ścierać kurz', english: 'to dust' },
      { polish: 'jeść', english: 'to eat' },
      { polish: 'wyrzucić śmieci', english: 'to empty the bin' },
      { polish: 'ćwiczyć', english: 'to exercise' },
      { polish: 'zasypiać', english: 'to fall asleep' },
      { polish: 'wpaść w rutynę', english: 'to fall into routine' },
      { polish: 'ubierać się', english: 'to get dressed' },
      { polish: 'iść pobiegać', english: 'to go jogging' },
      { polish: 'iść na zakupy', english: 'to go shopping' },
      { polish: 'plotkować', english: 'to gossip' },
      { polish: 'kąpać się', english: 'to have a bath' },
      { polish: 'pomagać', english: 'to help' },
      { polish: 'odkurzać', english: 'to hoover' },
      { polish: 'prasować', english: 'to iron' },
      { polish: 'słuchać muzyki', english: 'to listen to music' },
      { polish: 'ścielić łóżko', english: 'to make the bed' },
      { polish: 'spotkać', english: 'to meet' },
      { polish: 'drzemka', english: 'nap' },
      { polish: 'czytać książkę', english: 'to read a book' },
      { polish: 'relaks', english: 'relaxation' },
      { polish: 'odpoczynek', english: 'rest' },
      { polish: 'rutyna', english: 'routine' },
      { polish: 'golić się', english: 'to shave' },
      { polish: 'spać', english: 'to sleep' },
      { polish: 'zamiatać', english: 'to sweep' },
      { polish: 'brać prysznic', english: 'to take a shower' },
      { polish: 'rozebrać się', english: 'to undress' },
      { polish: 'czekać na autobus', english: 'to wait for a bus' },
      { polish: 'budzić się', english: 'to wake up' },
      { polish: 'chodzić / spacerować', english: 'to walk' },
      { polish: 'wyprowadzać psa / wyprowadzić psa', english: 'to walk the dog' },
      { polish: 'prać', english: 'to wash' },
      { polish: 'zmywać naczynia', english: 'to wash up the dishes' },
      { polish: 'oglądać telewizję', english: 'to watch television' },
      { polish: 'pisać', english: 'to write' },
    ],
    name: {
      english: 'Daily Activities',
      polish: 'Codzienne czynności',
    },
    Icon: Calendar,
  },
  babiesAndPregnancy: {
    value: [
      { polish: 'niemowlę / dziecko', english: 'baby' },
      { polish: 'chłopczyk', english: 'baby boy' },
      { polish: 'dziewczynka', english: 'baby girl' },
      { polish: 'niemowlęctwo / okres niemowlęcy', english: 'babyhood' },
      { polish: 'dziecinny', english: 'babyish' },
      { polish: 'śliniaczek', english: 'bib' },
      { polish: 'karmić piersią', english: 'to breast-feed' },
      { polish: 'cesarskie cięcie', english: 'Caesarean section' },
      { polish: 'przewijać niemowlę', english: 'to change a baby' },
      { polish: 'dziecko', english: 'child' },
      { polish: 'opieka nad dzieckiem', english: 'child-mind' },
      { polish: 'dziecinny', english: 'childish' },
      { polish: 'dzieci', english: 'children' },
      { polish: 'kołyska', english: 'cradle' },
      { polish: 'nie bądź dzieckiem!', english: "don't be a baby!" },
      { polish: 'ślinić się', english: 'to dribble' },
      { polish: 'smoczek', english: 'dummy' },
      { polish: 'przyszła matka', english: 'expectant mother' },
      { polish: 'butelka dla niemowląt', english: 'feeding bootle' },
      { polish: 'zajść w ciążę', english: 'to get pregnant' },
      { polish: 'niemowlęctwo', english: 'infancy' },
      { polish: 'niemowlę', english: 'infant' },
      { polish: 'bóle porodowe', english: 'labour pains' },
      { polish: 'wyprawka niemowlęca', english: 'layette' },
      { polish: 'kołysanka', english: 'lullaby' },
      { polish: 'macierzyński', english: 'maternal' },
      { polish: 'macierzyństwo', english: 'maternity' },
      { polish: 'suknia ciążowa', english: 'maternity dress' },
      { polish: 'szpital położniczy', english: 'maternity hospital' },
      { polish: 'przyszła matka', english: 'mother-to-be' },
      { polish: 'macierzyństwo', english: 'motherhood' },
      { polish: 'macierzyński / matczyny', english: 'motherly' },
      { polish: 'pieluszka', english: 'nappy' },
      { polish: 'odparzenie od pieluszki', english: 'nappy rash' },
      { polish: 'poród naturalny', english: 'natural childbirth' },
      { polish: 'poporodowy', english: 'postnatal' },
      { polish: 'wózek dziecięcy', english: 'pram' },
      { polish: 'ciąża', english: 'pregnancy' },
      { polish: 'test ciążowy', english: 'pregnancy test' },
      { polish: 'w ciąży', english: 'pregnant' },
      { polish: 'kobieta w ciąży', english: 'pregnant woman' },
      { polish: 'wcześniak', english: 'premature baby' },
      { polish: 'czworaczki', english: 'quadruplets' },
      { polish: 'pięcioraczki', english: 'quintuplets' },
      { polish: 'pajacyk (ubranie)', english: 'rompers' },
      { polish: 'huśtawka', english: 'seesaw' },
      { polish: 'łopatka', english: 'spade' },
      { polish: 'dawać klapsa / dać klapsa', english: 'to spank' },
      { polish: 'pluszowa zabawka', english: 'stuffed toy' },
      { polish: 'karmić piersią', english: 'to suckle' },
      { polish: 'dziecko jest pod moją opieką', english: 'the child is in my care' },
      { polish: 'w trzecim miesiącu ciąży', english: 'three months pregnant' },
      { polish: 'brzdąc / berbeć', english: 'toddler' },
      { polish: 'szkrab / brzdąc', english: 'tot' },
      { polish: 'zabawka', english: 'toy' },
      { polish: 'samochodzik', english: 'toy car' },
      { polish: 'żołnierzyk', english: 'toy soldier' },
      { polish: 'trojaczki', english: 'triplets' },
    ],
    name: {
      english: 'Babies and Pregnancy',
      polish: 'Dzieci i ciąża',
    },
    Icon: Baby,
  },
};
